#!/usr/bin/env ruby
require "bundler/setup"
require "cloudmunda/cli"

begin
  cli = ::Cloudmunda::CLI.instance
  cli.parse
  cli.run
rescue => e
  raise e if $DEBUG
  STDERR.puts e.message
  STDERR.puts e.backtrace.join("\n")
  exit 1
end
